/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.liferay.sample.model.Empleado;
import com.liferay.sample.model.EmpleadoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Empleado service. Represents a row in the &quot;ge_Empleado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.sample.model.EmpleadoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpleadoImpl}.
 * </p>
 *
 * @author anadlca
 * @see EmpleadoImpl
 * @see com.liferay.sample.model.Empleado
 * @see com.liferay.sample.model.EmpleadoModel
 * @generated
 */
public class EmpleadoModelImpl extends BaseModelImpl<Empleado>
	implements EmpleadoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a empleado model instance should use the {@link com.liferay.sample.model.Empleado} interface instead.
	 */
	public static final String TABLE_NAME = "ge_Empleado";
	public static final Object[][] TABLE_COLUMNS = {
			{ "idEmpleado", Types.INTEGER },
			{ "nombre", Types.VARCHAR },
			{ "telefono", Types.VARCHAR },
			{ "idDepartamento", Types.INTEGER },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ge_Empleado (idEmpleado INTEGER not null primary key,nombre VARCHAR(75) null,telefono VARCHAR(75) null,idDepartamento INTEGER,companyId LONG,groupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ge_Empleado";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.sample.model.Empleado"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.sample.model.Empleado"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.sample.model.Empleado"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.sample.model.Empleado"));

	public EmpleadoModelImpl() {
	}

	public int getPrimaryKey() {
		return _idEmpleado;
	}

	public void setPrimaryKey(int primaryKey) {
		setIdEmpleado(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_idEmpleado);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return Empleado.class;
	}

	public String getModelClassName() {
		return Empleado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idEmpleado", getIdEmpleado());
		attributes.put("nombre", getNombre());
		attributes.put("telefono", getTelefono());
		attributes.put("idDepartamento", getIdDepartamento());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer idEmpleado = (Integer)attributes.get("idEmpleado");

		if (idEmpleado != null) {
			setIdEmpleado(idEmpleado);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}

		String telefono = (String)attributes.get("telefono");

		if (telefono != null) {
			setTelefono(telefono);
		}

		Integer idDepartamento = (Integer)attributes.get("idDepartamento");

		if (idDepartamento != null) {
			setIdDepartamento(idDepartamento);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}
	}

	public int getIdEmpleado() {
		return _idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		_idEmpleado = idEmpleado;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	public String getTelefono() {
		if (_telefono == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefono;
		}
	}

	public void setTelefono(String telefono) {
		_telefono = telefono;
	}

	public int getIdDepartamento() {
		return _idDepartamento;
	}

	public void setIdDepartamento(int idDepartamento) {
		_idDepartamento = idDepartamento;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Empleado toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Empleado)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		EmpleadoImpl empleadoImpl = new EmpleadoImpl();

		empleadoImpl.setIdEmpleado(getIdEmpleado());
		empleadoImpl.setNombre(getNombre());
		empleadoImpl.setTelefono(getTelefono());
		empleadoImpl.setIdDepartamento(getIdDepartamento());
		empleadoImpl.setCompanyId(getCompanyId());
		empleadoImpl.setGroupId(getGroupId());

		empleadoImpl.resetOriginalValues();

		return empleadoImpl;
	}

	public int compareTo(Empleado empleado) {
		int primaryKey = empleado.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Empleado empleado = null;

		try {
			empleado = (Empleado)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = empleado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EmpleadoModelImpl empleadoModelImpl = this;

		empleadoModelImpl._originalGroupId = empleadoModelImpl._groupId;

		empleadoModelImpl._setOriginalGroupId = false;

		empleadoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Empleado> toCacheModel() {
		EmpleadoCacheModel empleadoCacheModel = new EmpleadoCacheModel();

		empleadoCacheModel.idEmpleado = getIdEmpleado();

		empleadoCacheModel.nombre = getNombre();

		String nombre = empleadoCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			empleadoCacheModel.nombre = null;
		}

		empleadoCacheModel.telefono = getTelefono();

		String telefono = empleadoCacheModel.telefono;

		if ((telefono != null) && (telefono.length() == 0)) {
			empleadoCacheModel.telefono = null;
		}

		empleadoCacheModel.idDepartamento = getIdDepartamento();

		empleadoCacheModel.companyId = getCompanyId();

		empleadoCacheModel.groupId = getGroupId();

		return empleadoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{idEmpleado=");
		sb.append(getIdEmpleado());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append(", telefono=");
		sb.append(getTelefono());
		sb.append(", idDepartamento=");
		sb.append(getIdDepartamento());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.sample.model.Empleado");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idEmpleado</column-name><column-value><![CDATA[");
		sb.append(getIdEmpleado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefono</column-name><column-value><![CDATA[");
		sb.append(getTelefono());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idDepartamento</column-name><column-value><![CDATA[");
		sb.append(getIdDepartamento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Empleado.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Empleado.class
		};
	private int _idEmpleado;
	private String _nombre;
	private String _telefono;
	private int _idDepartamento;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private Empleado _escapedModelProxy;
}