/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.telefonica.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Empleado service. Represents a row in the &quot;ge_Empleado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.telefonica.model.impl.EmpleadoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.telefonica.model.impl.EmpleadoImpl}.
 * </p>
 *
 * @author anadlca
 * @see Empleado
 * @see com.telefonica.model.impl.EmpleadoImpl
 * @see com.telefonica.model.impl.EmpleadoModelImpl
 * @generated
 */
public interface EmpleadoModel extends BaseModel<Empleado> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a empleado model instance should use the {@link Empleado} interface instead.
	 */

	/**
	 * Returns the primary key of this empleado.
	 *
	 * @return the primary key of this empleado
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this empleado.
	 *
	 * @param primaryKey the primary key of this empleado
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id empleado of this empleado.
	 *
	 * @return the id empleado of this empleado
	 */
	public int getIdEmpleado();

	/**
	 * Sets the id empleado of this empleado.
	 *
	 * @param idEmpleado the id empleado of this empleado
	 */
	public void setIdEmpleado(int idEmpleado);

	/**
	 * Returns the nombre of this empleado.
	 *
	 * @return the nombre of this empleado
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this empleado.
	 *
	 * @param nombre the nombre of this empleado
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the telefono of this empleado.
	 *
	 * @return the telefono of this empleado
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this empleado.
	 *
	 * @param telefono the telefono of this empleado
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the id departamento of this empleado.
	 *
	 * @return the id departamento of this empleado
	 */
	public int getIdDepartamento();

	/**
	 * Sets the id departamento of this empleado.
	 *
	 * @param idDepartamento the id departamento of this empleado
	 */
	public void setIdDepartamento(int idDepartamento);

	/**
	 * Returns the url foto of this empleado.
	 *
	 * @return the url foto of this empleado
	 */
	@AutoEscape
	public String getUrlFoto();

	/**
	 * Sets the url foto of this empleado.
	 *
	 * @param urlFoto the url foto of this empleado
	 */
	public void setUrlFoto(String urlFoto);

	/**
	 * Returns the company ID of this empleado.
	 *
	 * @return the company ID of this empleado
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this empleado.
	 *
	 * @param companyId the company ID of this empleado
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this empleado.
	 *
	 * @return the group ID of this empleado
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this empleado.
	 *
	 * @param groupId the group ID of this empleado
	 */
	public void setGroupId(long groupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Empleado empleado);

	public int hashCode();

	public CacheModel<Empleado> toCacheModel();

	public Empleado toEscapedModel();

	public String toString();

	public String toXmlString();
}