/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.sample.model.Empleado;
import com.liferay.sample.service.DepartamentoLocalService;
import com.liferay.sample.service.EmpleadoLocalService;
import com.liferay.sample.service.persistence.DepartamentoPersistence;
import com.liferay.sample.service.persistence.EmpleadoPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the empleado local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.sample.service.impl.EmpleadoLocalServiceImpl}.
 * </p>
 *
 * @author anadlca
 * @see com.liferay.sample.service.impl.EmpleadoLocalServiceImpl
 * @see com.liferay.sample.service.EmpleadoLocalServiceUtil
 * @generated
 */
public abstract class EmpleadoLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements EmpleadoLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.sample.service.EmpleadoLocalServiceUtil} to access the empleado local service.
	 */

	/**
	 * Adds the empleado to the database. Also notifies the appropriate model listeners.
	 *
	 * @param empleado the empleado
	 * @return the empleado that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Empleado addEmpleado(Empleado empleado) throws SystemException {
		empleado.setNew(true);

		return empleadoPersistence.update(empleado, false);
	}

	/**
	 * Creates a new empleado with the primary key. Does not add the empleado to the database.
	 *
	 * @param idEmpleado the primary key for the new empleado
	 * @return the new empleado
	 */
	public Empleado createEmpleado(int idEmpleado) {
		return empleadoPersistence.create(idEmpleado);
	}

	/**
	 * Deletes the empleado with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param idEmpleado the primary key of the empleado
	 * @return the empleado that was removed
	 * @throws PortalException if a empleado with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Empleado deleteEmpleado(int idEmpleado)
		throws PortalException, SystemException {
		return empleadoPersistence.remove(idEmpleado);
	}

	/**
	 * Deletes the empleado from the database. Also notifies the appropriate model listeners.
	 *
	 * @param empleado the empleado
	 * @return the empleado that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Empleado deleteEmpleado(Empleado empleado) throws SystemException {
		return empleadoPersistence.remove(empleado);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Empleado.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return empleadoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return empleadoPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return empleadoPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return empleadoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Empleado fetchEmpleado(int idEmpleado) throws SystemException {
		return empleadoPersistence.fetchByPrimaryKey(idEmpleado);
	}

	/**
	 * Returns the empleado with the primary key.
	 *
	 * @param idEmpleado the primary key of the empleado
	 * @return the empleado
	 * @throws PortalException if a empleado with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Empleado getEmpleado(int idEmpleado)
		throws PortalException, SystemException {
		return empleadoPersistence.findByPrimaryKey(idEmpleado);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return empleadoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the empleados.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of empleados
	 * @param end the upper bound of the range of empleados (not inclusive)
	 * @return the range of empleados
	 * @throws SystemException if a system exception occurred
	 */
	public List<Empleado> getEmpleados(int start, int end)
		throws SystemException {
		return empleadoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of empleados.
	 *
	 * @return the number of empleados
	 * @throws SystemException if a system exception occurred
	 */
	public int getEmpleadosCount() throws SystemException {
		return empleadoPersistence.countAll();
	}

	/**
	 * Updates the empleado in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param empleado the empleado
	 * @return the empleado that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Empleado updateEmpleado(Empleado empleado) throws SystemException {
		return updateEmpleado(empleado, true);
	}

	/**
	 * Updates the empleado in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param empleado the empleado
	 * @param merge whether to merge the empleado with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the empleado that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Empleado updateEmpleado(Empleado empleado, boolean merge)
		throws SystemException {
		empleado.setNew(false);

		return empleadoPersistence.update(empleado, merge);
	}

	/**
	 * Returns the departamento local service.
	 *
	 * @return the departamento local service
	 */
	public DepartamentoLocalService getDepartamentoLocalService() {
		return departamentoLocalService;
	}

	/**
	 * Sets the departamento local service.
	 *
	 * @param departamentoLocalService the departamento local service
	 */
	public void setDepartamentoLocalService(
		DepartamentoLocalService departamentoLocalService) {
		this.departamentoLocalService = departamentoLocalService;
	}

	/**
	 * Returns the departamento persistence.
	 *
	 * @return the departamento persistence
	 */
	public DepartamentoPersistence getDepartamentoPersistence() {
		return departamentoPersistence;
	}

	/**
	 * Sets the departamento persistence.
	 *
	 * @param departamentoPersistence the departamento persistence
	 */
	public void setDepartamentoPersistence(
		DepartamentoPersistence departamentoPersistence) {
		this.departamentoPersistence = departamentoPersistence;
	}

	/**
	 * Returns the empleado local service.
	 *
	 * @return the empleado local service
	 */
	public EmpleadoLocalService getEmpleadoLocalService() {
		return empleadoLocalService;
	}

	/**
	 * Sets the empleado local service.
	 *
	 * @param empleadoLocalService the empleado local service
	 */
	public void setEmpleadoLocalService(
		EmpleadoLocalService empleadoLocalService) {
		this.empleadoLocalService = empleadoLocalService;
	}

	/**
	 * Returns the empleado persistence.
	 *
	 * @return the empleado persistence
	 */
	public EmpleadoPersistence getEmpleadoPersistence() {
		return empleadoPersistence;
	}

	/**
	 * Sets the empleado persistence.
	 *
	 * @param empleadoPersistence the empleado persistence
	 */
	public void setEmpleadoPersistence(EmpleadoPersistence empleadoPersistence) {
		this.empleadoPersistence = empleadoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.liferay.sample.model.Empleado",
			empleadoLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.sample.model.Empleado");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return Empleado.class;
	}

	protected String getModelClassName() {
		return Empleado.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = empleadoPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = DepartamentoLocalService.class)
	protected DepartamentoLocalService departamentoLocalService;
	@BeanReference(type = DepartamentoPersistence.class)
	protected DepartamentoPersistence departamentoPersistence;
	@BeanReference(type = EmpleadoLocalService.class)
	protected EmpleadoLocalService empleadoLocalService;
	@BeanReference(type = EmpleadoPersistence.class)
	protected EmpleadoPersistence empleadoPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private EmpleadoLocalServiceClpInvoker _clpInvoker = new EmpleadoLocalServiceClpInvoker();
}